-- =========================================================
-- AXE HUB · AXE BUILD V1.1.18
-- SERVER-SIDE ANTI-SPAM / RATE LIMIT
-- Run once in AXE HUB > Supabase > SQL Editor
-- Requires the existing V1.1.0 schema. V1.1.15 remains required
-- if you use the company-name feature.
-- =========================================================

begin;

-- Internal event log. Clients receive no direct access.
create table if not exists public.axe_rate_limit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  created_at timestamptz not null default now()
);

create index if not exists axe_rate_limit_events_lookup_v118
  on public.axe_rate_limit_events(user_id, action, created_at desc);

alter table public.axe_rate_limit_events enable row level security;

revoke all on table public.axe_rate_limit_events from anon, authenticated;
revoke all on sequence public.axe_rate_limit_events_id_seq from anon, authenticated;

-- Normalize exact duplicate text checks.
create or replace function public.axe_hub_normalize_text_v118(p_value text)
returns text
language sql
immutable
as $$
  select lower(
    regexp_replace(
      btrim(coalesce(p_value, '')),
      '[[:space:]]+',
      ' ',
      'g'
    )
  );
$$;

-- User-friendly remaining wait text.
create or replace function public.axe_hub_wait_text_v118(p_seconds integer)
returns text
language sql
immutable
as $$
  select case
    when greatest(coalesce(p_seconds, 1), 1) < 60
      then greatest(coalesce(p_seconds, 1), 1)::text || '초'
    when greatest(coalesce(p_seconds, 1), 1) < 3600
      then ceil(greatest(coalesce(p_seconds, 1), 1) / 60.0)::integer::text || '분'
    else ceil(greatest(coalesce(p_seconds, 1), 1) / 3600.0)::integer::text || '시간'
  end;
$$;

-- Shared server-side rate limiter.
create or replace function public.axe_hub_enforce_rate_v118(
  p_action text,
  p_short_window interval,
  p_short_limit integer,
  p_daily_limit integer,
  p_action_label text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_now timestamptz := now();
  v_count integer;
  v_oldest timestamptz;
  v_wait integer;
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.';
  end if;

  -- Admin activity should never be blocked by public anti-spam rules.
  if public.axe_hub_is_admin(v_uid) then
    return;
  end if;

  if p_short_limit < 1 or p_daily_limit < 1 then
    raise exception 'rate-limit configuration error';
  end if;

  -- Serialize checks per user/action so parallel requests cannot bypass the limit.
  perform pg_advisory_xact_lock(
    hashtextextended(v_uid::text || ':' || p_action, 118)
  );

  -- Opportunistic cleanup, scoped to the current user.
  delete from public.axe_rate_limit_events
   where user_id = v_uid
     and created_at < v_now - interval '2 days';

  select count(*), min(created_at)
    into v_count, v_oldest
    from public.axe_rate_limit_events
   where user_id = v_uid
     and action = p_action
     and created_at > v_now - p_short_window;

  if v_count >= p_short_limit then
    v_wait := greatest(
      1,
      ceil(extract(epoch from ((v_oldest + p_short_window) - v_now)))::integer
    );

    raise exception '도배 방지: %은(는) 잠시 제한됩니다. % 후 다시 시도해주세요.',
      p_action_label,
      public.axe_hub_wait_text_v118(v_wait);
  end if;

  select count(*), min(created_at)
    into v_count, v_oldest
    from public.axe_rate_limit_events
   where user_id = v_uid
     and action = p_action
     and created_at > v_now - interval '24 hours';

  if v_count >= p_daily_limit then
    v_wait := greatest(
      1,
      ceil(extract(epoch from ((v_oldest + interval '24 hours') - v_now)))::integer
    );

    raise exception '도배 방지: %의 24시간 등록 한도에 도달했습니다. 약 % 후 다시 시도해주세요.',
      p_action_label,
      public.axe_hub_wait_text_v118(v_wait);
  end if;

  insert into public.axe_rate_limit_events(user_id, action, created_at)
  values (v_uid, p_action, v_now);
end;
$$;

-- =========================================================
-- BUILDS
-- 3 / 10 min, 15 / 24h
-- Exact duplicate title+summary+description blocked for 24h.
-- =========================================================
create or replace function public.axe_hub_guard_build_insert_v118()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if not public.axe_hub_is_admin(v_uid) then
    if new.author_id is distinct from v_uid then
      raise exception '작성자 정보가 올바르지 않습니다.';
    end if;

    perform public.axe_hub_enforce_rate_v118(
      'build_create',
      interval '10 minutes',
      3,
      15,
      '빌드 작성'
    );

    if exists (
      select 1
        from public.builds b
       where b.author_id = v_uid
         and b.created_at > now() - interval '24 hours'
         and public.axe_hub_normalize_text_v118(b.title)
             = public.axe_hub_normalize_text_v118(new.title)
         and public.axe_hub_normalize_text_v118(b.summary)
             = public.axe_hub_normalize_text_v118(new.summary)
         and public.axe_hub_normalize_text_v118(b.description)
             = public.axe_hub_normalize_text_v118(new.description)
    ) then
      raise exception '중복 등록 방지: 같은 내용의 빌드가 최근 24시간 안에 이미 등록되어 있습니다.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists axe_hub_guard_build_insert_v118 on public.builds;
create trigger axe_hub_guard_build_insert_v118
before insert on public.builds
for each row
execute function public.axe_hub_guard_build_insert_v118();

-- =========================================================
-- COMMENTS
-- 5 / 1 min, 80 / 24h
-- Same normalized comment on same build blocked for 10 min.
-- =========================================================
create or replace function public.axe_hub_guard_comment_insert_v118()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if not public.axe_hub_is_admin(v_uid) then
    if new.user_id is distinct from v_uid then
      raise exception '댓글 작성자 정보가 올바르지 않습니다.';
    end if;

    perform public.axe_hub_enforce_rate_v118(
      'comment_create',
      interval '1 minute',
      5,
      80,
      '댓글 등록'
    );

    if exists (
      select 1
        from public.build_comments c
       where c.user_id = v_uid
         and c.build_id = new.build_id
         and c.created_at > now() - interval '10 minutes'
         and public.axe_hub_normalize_text_v118(c.body)
             = public.axe_hub_normalize_text_v118(new.body)
    ) then
      raise exception '중복 등록 방지: 같은 댓글을 연속해서 등록할 수 없습니다.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists axe_hub_guard_comment_insert_v118 on public.build_comments;
create trigger axe_hub_guard_comment_insert_v118
before insert on public.build_comments
for each row
execute function public.axe_hub_guard_comment_insert_v118();

-- =========================================================
-- REPORTS
-- 3 / 10 min, 12 / 24h
-- Same report payload blocked for 24h.
-- =========================================================
create or replace function public.axe_hub_guard_report_insert_v118()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.';
  end if;

  if not public.axe_hub_is_admin(v_uid) then
    if new.reporter_id is distinct from v_uid then
      raise exception '제보자 정보가 올바르지 않습니다.';
    end if;

    perform public.axe_hub_enforce_rate_v118(
      'report_create',
      interval '10 minutes',
      3,
      12,
      '제보 등록'
    );

    if exists (
      select 1
        from public.modbook_reports r
       where r.reporter_id = v_uid
         and r.created_at > now() - interval '24 hours'
         and coalesce(r.report_type, '') = coalesce(new.report_type, '')
         and coalesce(r.target_modbook_id::text, '') = coalesce(new.target_modbook_id::text, '')
         and public.axe_hub_normalize_text_v118(r.name)
             = public.axe_hub_normalize_text_v118(new.name)
         and public.axe_hub_normalize_text_v118(r.options_text)
             = public.axe_hub_normalize_text_v118(new.options_text)
         and public.axe_hub_normalize_text_v118(r.note)
             = public.axe_hub_normalize_text_v118(new.note)
    ) then
      raise exception '중복 등록 방지: 같은 내용의 제보가 최근 24시간 안에 이미 등록되어 있습니다.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists axe_hub_guard_report_insert_v118 on public.modbook_reports;
create trigger axe_hub_guard_report_insert_v118
before insert on public.modbook_reports
for each row
execute function public.axe_hub_guard_report_insert_v118();

-- These functions are internal. Trigger execution does not need client grants.
revoke all on function public.axe_hub_normalize_text_v118(text) from public;
revoke all on function public.axe_hub_wait_text_v118(integer) from public;
revoke all on function public.axe_hub_enforce_rate_v118(text, interval, integer, integer, text) from public;
revoke all on function public.axe_hub_guard_build_insert_v118() from public;
revoke all on function public.axe_hub_guard_comment_insert_v118() from public;
revoke all on function public.axe_hub_guard_report_insert_v118() from public;

notify pgrst, 'reload schema';

commit;
