-- =========================================================
-- AXE HUB · AXE BUILD V1.1.0 SOCIAL / PRESET / NOTICE / NICKNAME
-- Run once in AXE HUB > SQL Editor before deploying V1.1.0
-- =========================================================
begin;

-- ---------- profile / build columns ----------
alter table public.profiles add column if not exists approved_nickname text;
alter table public.profiles add column if not exists nickname_updated_at timestamptz;

create unique index if not exists profiles_approved_nickname_unique_v110
  on public.profiles (lower(approved_nickname))
  where approved_nickname is not null;

alter table public.builds add column if not exists like_count integer not null default 0;
alter table public.builds add column if not exists dislike_count integer not null default 0;
alter table public.builds add column if not exists comment_count integer not null default 0;

-- ---------- admin helper ----------
create or replace function public.axe_hub_is_admin(p_uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = p_uid), false);
$$;

revoke all on function public.axe_hub_is_admin(uuid) from public;
grant execute on function public.axe_hub_is_admin(uuid) to anon, authenticated;

-- ---------- votes ----------
create table if not exists public.build_votes (
  build_id uuid not null references public.builds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (build_id, user_id)
);

alter table public.build_votes enable row level security;

drop policy if exists axe_votes_select_own_v110 on public.build_votes;
create policy axe_votes_select_own_v110 on public.build_votes for select to authenticated using (user_id = auth.uid());
drop policy if exists axe_votes_insert_own_v110 on public.build_votes;
create policy axe_votes_insert_own_v110 on public.build_votes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists axe_votes_update_own_v110 on public.build_votes;
create policy axe_votes_update_own_v110 on public.build_votes for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
drop policy if exists axe_votes_delete_own_v110 on public.build_votes;
create policy axe_votes_delete_own_v110 on public.build_votes for delete to authenticated using (user_id = auth.uid());

grant select, insert, update, delete on public.build_votes to authenticated;

create or replace function public.refresh_build_vote_counts_v110(p_build_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.builds b
     set like_count = (select count(*) from public.build_votes v where v.build_id = p_build_id and v.value = 1),
         dislike_count = (select count(*) from public.build_votes v where v.build_id = p_build_id and v.value = -1)
   where b.id = p_build_id;
$$;

create or replace function public.build_votes_sync_counts_v110()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op in ('UPDATE','DELETE') then perform public.refresh_build_vote_counts_v110(old.build_id); end if;
  if tg_op in ('INSERT','UPDATE') then perform public.refresh_build_vote_counts_v110(new.build_id); end if;
  return null;
end;
$$;

drop trigger if exists build_votes_sync_counts_v110 on public.build_votes;
create trigger build_votes_sync_counts_v110 after insert or update or delete on public.build_votes for each row execute function public.build_votes_sync_counts_v110();

create or replace function public.set_build_vote(p_build_id uuid, p_value smallint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'login required'; end if;
  if p_value not in (-1, 0, 1) then raise exception 'invalid vote'; end if;
  if p_value = 0 then
    delete from public.build_votes where build_id = p_build_id and user_id = auth.uid();
  else
    insert into public.build_votes(build_id, user_id, value)
    values (p_build_id, auth.uid(), p_value)
    on conflict (build_id, user_id) do update set value = excluded.value, updated_at = now();
  end if;
end;
$$;
grant execute on function public.set_build_vote(uuid, smallint) to authenticated;

-- ---------- comments ----------
create table if not exists public.build_comments (
  id bigint generated by default as identity primary key,
  build_id uuid not null references public.builds(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  author_name text not null,
  body text not null check (char_length(btrim(body)) between 1 and 500),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists build_comments_build_created_idx_v110 on public.build_comments(build_id, created_at);
alter table public.build_comments enable row level security;

drop policy if exists axe_comments_public_read_v110 on public.build_comments;
create policy axe_comments_public_read_v110 on public.build_comments for select to anon, authenticated using (true);
drop policy if exists axe_comments_insert_own_v110 on public.build_comments;
create policy axe_comments_insert_own_v110 on public.build_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists axe_comments_update_own_v110 on public.build_comments;
create policy axe_comments_update_own_v110 on public.build_comments for update to authenticated using (user_id = auth.uid() or public.axe_hub_is_admin(auth.uid())) with check (user_id = auth.uid() or public.axe_hub_is_admin(auth.uid()));
drop policy if exists axe_comments_delete_own_admin_v110 on public.build_comments;
create policy axe_comments_delete_own_admin_v110 on public.build_comments for delete to authenticated using (user_id = auth.uid() or public.axe_hub_is_admin(auth.uid()));

grant select on public.build_comments to anon;
grant select, insert, update, delete on public.build_comments to authenticated;
grant usage, select on sequence public.build_comments_id_seq to authenticated;

create or replace function public.refresh_build_comment_count_v110(p_build_id uuid)
returns void language sql security definer set search_path = public as $$
  update public.builds set comment_count = (select count(*) from public.build_comments c where c.build_id = p_build_id) where id = p_build_id;
$$;
create or replace function public.build_comments_sync_count_v110()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op = 'DELETE' then perform public.refresh_build_comment_count_v110(old.build_id); else perform public.refresh_build_comment_count_v110(new.build_id); end if;
  return null;
end;
$$;
drop trigger if exists build_comments_sync_count_v110 on public.build_comments;
create trigger build_comments_sync_count_v110 after insert or delete on public.build_comments for each row execute function public.build_comments_sync_count_v110();

-- ---------- announcements ----------
create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(btrim(title)) between 1 and 120),
  body text not null check (char_length(btrim(body)) between 1 and 2000),
  is_pinned boolean not null default false,
  is_published boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.announcements enable row level security;
drop policy if exists axe_announcements_public_read_v110 on public.announcements;
create policy axe_announcements_public_read_v110 on public.announcements for select to anon, authenticated using (is_published or public.axe_hub_is_admin(auth.uid()));
drop policy if exists axe_announcements_admin_insert_v110 on public.announcements;
create policy axe_announcements_admin_insert_v110 on public.announcements for insert to authenticated with check (public.axe_hub_is_admin(auth.uid()));
drop policy if exists axe_announcements_admin_update_v110 on public.announcements;
create policy axe_announcements_admin_update_v110 on public.announcements for update to authenticated using (public.axe_hub_is_admin(auth.uid())) with check (public.axe_hub_is_admin(auth.uid()));
drop policy if exists axe_announcements_admin_delete_v110 on public.announcements;
create policy axe_announcements_admin_delete_v110 on public.announcements for delete to authenticated using (public.axe_hub_is_admin(auth.uid()));
grant select on public.announcements to anon;
grant select, insert, update, delete on public.announcements to authenticated;
grant usage, select on sequence public.announcements_id_seq to authenticated;

insert into public.announcements(title, body, is_pinned, is_published)
select 'AXE BUILD 안내', 'AXE BUILD의 변경사항과 데이터 업데이트 안내는 이 공지사항에서 확인할 수 있습니다.', true, true
where not exists (select 1 from public.announcements);

-- ---------- nickname requests ----------
create table if not exists public.nickname_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  requested_name text not null,
  current_name text,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  admin_note text,
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null
);
alter table public.nickname_requests add column if not exists current_name text;
create index if not exists nickname_requests_user_created_idx_v110 on public.nickname_requests(user_id, created_at desc);
create unique index if not exists nickname_requests_one_pending_v110 on public.nickname_requests(user_id) where status = 'pending';
alter table public.nickname_requests enable row level security;
drop policy if exists axe_nickname_own_or_admin_read_v110 on public.nickname_requests;
create policy axe_nickname_own_or_admin_read_v110 on public.nickname_requests for select to authenticated using (user_id = auth.uid() or public.axe_hub_is_admin(auth.uid()));
grant select on public.nickname_requests to authenticated;
grant usage, select on sequence public.nickname_requests_id_seq to authenticated;

create or replace function public.request_nickname(p_requested_name text)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := btrim(p_requested_name);
  v_id bigint;
begin
  if auth.uid() is null then raise exception 'login required'; end if;
  if char_length(v_name) < 2 or char_length(v_name) > 16 then raise exception '닉네임은 2~16자여야 합니다.'; end if;
  if v_name !~ '^[가-힣A-Za-z0-9 _-]+$' then raise exception '닉네임에는 한글, 영문, 숫자, 공백, _, - 만 사용할 수 있습니다.'; end if;
  if exists (select 1 from public.profiles where approved_nickname is not null and lower(approved_nickname) = lower(v_name) and id <> auth.uid()) then raise exception '이미 사용 중인 닉네임입니다.'; end if;
  delete from public.nickname_requests where user_id = auth.uid() and status = 'pending';
  insert into public.nickname_requests(user_id, requested_name, current_name)
  select auth.uid(), v_name, coalesce(approved_nickname, display_name, 'Discord User')
  from public.profiles where id = auth.uid()
  returning id into v_id;
  if v_id is null then
    insert into public.nickname_requests(user_id, requested_name, current_name) values (auth.uid(), v_name, 'Discord User') returning id into v_id;
  end if;
  return v_id;
end;
$$;
grant execute on function public.request_nickname(text) to authenticated;

create or replace function public.review_nickname_request(p_request_id bigint, p_approve boolean, p_admin_note text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  r public.nickname_requests%rowtype;
begin
  if not public.axe_hub_is_admin(auth.uid()) then raise exception 'admin only'; end if;
  select * into r from public.nickname_requests where id = p_request_id for update;
  if r.id is null then raise exception 'request not found'; end if;
  if r.status <> 'pending' then raise exception 'already reviewed'; end if;

  if p_approve then
    if exists (select 1 from public.profiles where approved_nickname is not null and lower(approved_nickname) = lower(r.requested_name) and id <> r.user_id) then raise exception '이미 사용 중인 닉네임입니다.'; end if;
    update public.profiles set approved_nickname = r.requested_name, nickname_updated_at = now() where id = r.user_id;
    update public.builds set author_name = r.requested_name where author_id = r.user_id;
    update public.build_comments set author_name = r.requested_name where user_id = r.user_id;
    update public.nickname_requests set status = 'approved', admin_note = p_admin_note, reviewed_at = now(), reviewed_by = auth.uid() where id = r.id;
  else
    update public.nickname_requests set status = 'rejected', admin_note = p_admin_note, reviewed_at = now(), reviewed_by = auth.uid() where id = r.id;
  end if;
end;
$$;
grant execute on function public.review_nickname_request(bigint, boolean, text) to authenticated;

-- ---------- owner/admin build edit/delete safety ----------
grant select, insert, update, delete on public.builds to authenticated;
grant select, insert, update, delete on public.build_slots to authenticated;

drop policy if exists axe_build_owner_admin_update_v110 on public.builds;
create policy axe_build_owner_admin_update_v110 on public.builds for update to authenticated using (author_id = auth.uid() or public.axe_hub_is_admin(auth.uid())) with check (author_id = auth.uid() or public.axe_hub_is_admin(auth.uid()));
drop policy if exists axe_build_owner_admin_delete_v110 on public.builds;
create policy axe_build_owner_admin_delete_v110 on public.builds for delete to authenticated using (author_id = auth.uid() or public.axe_hub_is_admin(auth.uid()));

drop policy if exists axe_build_slots_owner_admin_insert_v110 on public.build_slots;
create policy axe_build_slots_owner_admin_insert_v110 on public.build_slots for insert to authenticated with check (exists (select 1 from public.builds b where b.id = build_id and (b.author_id = auth.uid() or public.axe_hub_is_admin(auth.uid()))));

drop policy if exists axe_build_slots_owner_admin_update_v110 on public.build_slots;
create policy axe_build_slots_owner_admin_update_v110 on public.build_slots for update to authenticated using (exists (select 1 from public.builds b where b.id = build_id and (b.author_id = auth.uid() or public.axe_hub_is_admin(auth.uid())))) with check (exists (select 1 from public.builds b where b.id = build_id and (b.author_id = auth.uid() or public.axe_hub_is_admin(auth.uid()))));
drop policy if exists axe_build_slots_owner_admin_delete_v110 on public.build_slots;
create policy axe_build_slots_owner_admin_delete_v110 on public.build_slots for delete to authenticated using (exists (select 1 from public.builds b where b.id = build_id and (b.author_id = auth.uid() or public.axe_hub_is_admin(auth.uid()))));

-- initialize counts
update public.builds b set
  like_count = (select count(*) from public.build_votes v where v.build_id=b.id and v.value=1),
  dislike_count = (select count(*) from public.build_votes v where v.build_id=b.id and v.value=-1),
  comment_count = (select count(*) from public.build_comments c where c.build_id=b.id);

notify pgrst, 'reload schema';
commit;
