-- AXE PRODUCT 3.26.4
-- PLATFORM OWNER company hard-delete RPC + deletion audit
-- PRODUCT STAGING only. Apply before WEB 3.26.4.

begin;

create table if not exists axe_product.platform_company_deletion_log (
  id bigint generated by default as identity primary key,
  company_id uuid not null,
  company_name text not null,
  company_slug text,
  deleted_by uuid references auth.users(id) on delete set null,
  deleted_at timestamptz not null default now()
);

alter table axe_product.platform_company_deletion_log enable row level security;
revoke all on table axe_product.platform_company_deletion_log from public, anon, authenticated;

create index if not exists idx_platform_company_deletion_log_deleted_at
  on axe_product.platform_company_deletion_log(deleted_at desc);

create or replace function axe_product.platform_admin_delete_company(
  p_company_id uuid,
  p_confirm_name text
)
returns jsonb
language plpgsql
security definer
set search_path to ''
as $$
declare
  v_uid uuid := auth.uid();
  v_company axe_product.companies%rowtype;
  v_confirm text := btrim(coalesce(p_confirm_name, ''));
begin
  if v_uid is null then
    raise exception '로그인이 필요합니다.' using errcode = '42501';
  end if;

  if not axe_product.platform_is_admin() then
    raise exception 'PLATFORM OWNER 권한이 필요합니다.' using errcode = '42501';
  end if;

  if p_company_id is null then
    raise exception '삭제할 회사를 확인하지 못했습니다.' using errcode = '22023';
  end if;

  select c.*
  into v_company
  from axe_product.companies c
  where c.id = p_company_id
  for update;

  if not found then
    raise exception '이미 삭제되었거나 존재하지 않는 회사입니다.' using errcode = 'P0002';
  end if;

  if v_confirm = '' or v_confirm <> btrim(v_company.name) then
    raise exception '회사 이름이 일치하지 않습니다.' using errcode = '22023';
  end if;

  -- Keep a minimal platform-level audit record outside the company FK tree.
  insert into axe_product.platform_company_deletion_log(
    company_id,
    company_name,
    company_slug,
    deleted_by
  ) values (
    v_company.id,
    v_company.name,
    v_company.slug,
    v_uid
  );

  -- Current axe_product company-owned tables use ON DELETE CASCADE.
  -- The parent delete therefore removes memberships, settings, modules,
  -- Discord connection metadata, fund/assets/accounts/support data, etc.
  delete from axe_product.companies c
  where c.id = v_company.id;

  if not found then
    raise exception '회사 삭제 상태를 확인하지 못했습니다.' using errcode = 'P0002';
  end if;

  return jsonb_build_object(
    'deleted', true,
    'company_id', v_company.id,
    'company_name', v_company.name,
    'deleted_at', now()
  );
exception
  when foreign_key_violation then
    raise exception '회사와 연결된 데이터 때문에 안전하게 삭제할 수 없습니다. 최신 DB 마이그레이션 상태를 확인해 주세요.'
      using errcode = '23503';
end;
$$;

revoke all on function axe_product.platform_admin_delete_company(uuid,text) from public;
revoke all on function axe_product.platform_admin_delete_company(uuid,text) from anon;
grant execute on function axe_product.platform_admin_delete_company(uuid,text) to authenticated;
grant execute on function axe_product.platform_admin_delete_company(uuid,text) to service_role;

comment on function axe_product.platform_admin_delete_company(uuid,text) is
'AXE PRODUCT 3.26.4: PLATFORM OWNER only hard delete. Requires exact company-name confirmation and records a deletion audit row.';

commit;
