import fs from 'node:fs';import path from 'node:path';import {chromium} from 'playwright';import {PNG} from 'pngjs';import pixelmatch from 'pixelmatch';
import {root,out,write,hash} from './common.mjs';import {serve} from './server.mjs';import {fixture,cases} from '../../tests/validation/fixtures.mjs';
const record=process.argv.includes('--record'), recordGeometry=process.argv.includes('--record-geometry'), baseline=path.join(root,'tests/validation/baselines');
const runtimeExecutable=process.env.AXE_CHROMIUM_PATH||(fs.existsSync(path.join(root,'node_modules/.cache/axe-validation/chromium'))?path.join(root,'node_modules/.cache/axe-validation/chromium'):null);
const checks=[],defects=[],visual=[],interactions=[],interactionEvidence=[],metrics=[],errors=[];let browser;
try{browser=await chromium.launch({headless:true,...(runtimeExecutable?{executablePath:runtimeExecutable,args:['--no-sandbox','--disable-dev-shm-usage']}: {})});}catch(e){for(const name of ['browser','visual','interaction'])write(name,{status:'NOT RUN',reason:e.message});process.exit(2);}
const host=await serve(), prod=fs.existsSync(path.join(root,'dist/index.html'))?await serve({production:true}):null;
fs.mkdirSync(baseline,{recursive:true});fs.mkdirSync(path.join(out,'screenshots'),{recursive:true});
const context=await browser.newContext({locale:'ko-KR',timezoneId:'UTC',deviceScaleFactor:1,colorScheme:'dark',reducedMotion:'reduce'});
await context.route('**/*',route=>{const url=route.request().url();return url.startsWith(host.url+'/')||(prod&&url.startsWith(prod.url+'/'))||url.startsWith('data:')?route.continue():route.abort('blockedbyclient');});
await context.addInitScript(()=>{const OriginalDate=Date;globalThis.Date=class extends OriginalDate{constructor(...args){super(...(args.length?args:['2026-09-16T12:00:00Z']));}static now(){return new OriginalDate('2026-09-16T12:00:00Z').getTime();}};});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const check=(name,ok,detail)=>checks.push({name,ok,detail});
async function reset(patch){await page.evaluate(next=>window.__axeTest.reset(next),fixture(patch));await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function measure(name,contract,width){
 const result=await page.evaluate(({name,contract,width})=>{
  const r=e=>{const b=e.getBoundingClientRect();return {x:b.x,y:b.y,w:b.width,h:b.height};};const main=document.querySelector('.main');
  const data={name,width,main:r(main),documentOverflow:document.documentElement.scrollWidth>innerWidth+1,font:getComputedStyle(document.body).fontFamily,containers:[...document.querySelectorAll('.axe-fund-ledger,.ops-mgmt-board,.platform-board,.ops-settings-page,.ops-cooking-settings')].map(e=>({class:e.className,...r(e),scrollWidth:e.scrollWidth,clientWidth:e.clientWidth}))};
  data.clippedButtons=[...document.querySelectorAll('.main button')].filter(e=>{if(!e.getClientRects().length)return false;let p=e.parentElement;const b=e.getBoundingClientRect();while(p&&p!==document.body){const c=getComputedStyle(p),v=p.getBoundingClientRect();if(/hidden|clip/.test(c.overflowX)&&(b.left<v.left-1||b.right>v.right+1))return true;p=p.parentElement;}return false;}).map(e=>({text:e.textContent.trim(),...r(e)}));
  if(contract){const [hs,rs,count,action]=contract,h=document.querySelector(hs),rows=[...document.querySelectorAll(rs)],row=rows[0];data.contract={headerCount:h?.children.length,rowCounts:rows.map(e=>e.children.length),expected:count,actionPresent:!action||rows.every(e=>e.querySelector(action)),headerDisplay:h&&getComputedStyle(h).display,headerGrid:h&&getComputedStyle(h).gridTemplateColumns,rowGrid:row&&getComputedStyle(row).gridTemplateColumns,headerCells:h?[...h.children].map(r):[],rowCells:row?[...row.children].map(r):[],mobileLabels:row?[...row.children].map(e=>e.dataset.label||null):[]};}
  return data;
 },{name,contract,width});
 metrics.push(result);const defectStart=defects.length;check(`${name}/${width}: CSS applied`,await page.locator('.runtime-app').evaluate(e=>getComputedStyle(e).minHeight!=='0px'&&getComputedStyle(document.body).backgroundColor!=='rgba(0, 0, 0, 0)'));
 if(contract){const c=result.contract;check(`${name}/${width}: header cells`,c.headerCount===contract[2],c.headerCount);check(`${name}/${width}: row cells`,c.rowCounts.length>0&&c.rowCounts.every(n=>n===contract[2]),c.rowCounts);check(`${name}/${width}: action`,c.actionPresent);
  if(width>760){check(`${name}/${width}: shared computed column model`,c.headerGrid===c.rowGrid,{head:c.headerGrid,row:c.rowGrid});const aligned=c.headerCells.every((h,i)=>Math.abs(h.x+h.w/2-(c.rowCells[i].x+c.rowCells[i].w/2))<=1);if(!aligned)defects.push({id:'axis-mismatch',name,width,detail:c});}
  if(name==='weekly'&&width<=760){const ys=c.rowCells.map(c=>c.y);if(Math.max(...ys)-Math.min(...ys)>10)defects.push({id:'weekly-mobile-seven-cells-six-tracks',name,width,detail:c});}
 }
 if(result.documentOverflow)defects.push({id:'document-horizontal-overflow',name,width});if(result.clippedButtons.length)defects.push({id:'button-clipping',name,width,buttons:result.clippedButtons});if(defects.length>defectStart)await page.screenshot({path:path.join(out,'screenshots',`defect-${name}-${width}.png`),fullPage:true,animations:'disabled'});return result;
}
try{
 await page.goto(host.url+'/__validation/');await page.waitForFunction(()=>window.__axeTest);
 // Freeze environment metadata; recordings require explicit command and never auto-update on compare.
 const cdp=await context.newCDPSession(page);await cdp.send('DOM.enable');await cdp.send('CSS.enable');await reset({page:'members'});const dom=await cdp.send('DOM.getDocument');const node=await cdp.send('DOM.querySelector',{nodeId:dom.root.nodeId,selector:'.page-header h1'});const usedFonts=await cdp.send('CSS.getPlatformFontsForNode',{nodeId:node.nodeId});check('Korean font available',usedFonts.fonts.some(f=>f.familyName.includes('Pretendard')));
 const environment={fonts:usedFonts.fonts.map(f=>f.familyName).sort(),fontPackage:'pretendard@1.3.9',browser:browser.version(),playwright:JSON.parse(fs.readFileSync(path.join(root,'node_modules/playwright/package.json'))).version,platform:process.platform,arch:process.arch,locale:'ko-KR',timezone:'UTC',dpr:1};
 if(record)fs.writeFileSync(path.join(baseline,'environment.json'),JSON.stringify(environment,null,2));
 const savedEnv=fs.existsSync(path.join(baseline,'environment.json'))?JSON.parse(fs.readFileSync(path.join(baseline,'environment.json'))):null;
 const sameEnv=JSON.stringify(savedEnv)===JSON.stringify(environment);
 for(const [size,viewport] of [['desktop',{width:1440,height:1000}],['mobile',{width:390,height:844}]]){
  await page.setViewportSize(viewport);
  for(const [name,patch,contract] of cases){await reset(patch);await measure(name,contract,viewport.width);
   if(name==='empty-members')check(`empty-state/${size}`,await page.locator('.ops-mgmt-empty').count()===1&&await page.locator('.ops-lane-row--member').count()===0);
   if(name.startsWith('empty-')&&name!=='empty-members')check(`${name}/${size}: empty structure`,await page.locator('.ops-mgmt-empty,.axe-fund-ledger-empty,.ops-cooking-menu-empty').count()===1&&await page.locator('.ops-lane-row,.axe-fund-ledger-row,.ops-cooking-menu-row,.platform-company-row').count()===0);
   if(name==='modal')check(`modal/${size}`,await page.locator('[role="dialog"]').isVisible());
   const file=`${size}-${name}.png`,actual=await page.screenshot({fullPage:true,animations:'disabled'});fs.writeFileSync(path.join(out,'screenshots',file),actual);
   if(record){fs.writeFileSync(path.join(baseline,file),actual);visual.push({name:file,status:'RECORDED'});}else if(!fs.existsSync(path.join(baseline,file))||!sameEnv){visual.push({name:file,status:'NOT RUN',reason:!sameEnv?'Baseline environment missing/mismatch':'Baseline missing'});}else{const a=PNG.sync.read(actual),b=PNG.sync.read(fs.readFileSync(path.join(baseline,file)));let diffCount=-1;if(a.width===b.width&&a.height===b.height){const diff=new PNG({width:a.width,height:a.height});diffCount=pixelmatch(a.data,b.data,diff.data,a.width,a.height,{threshold:0,includeAA:true});if(diffCount)fs.writeFileSync(path.join(out,'screenshots',file.replace('.png','-diff.png')),PNG.sync.write(diff));}visual.push({name:file,status:diffCount>=0&&diffCount<=4?'PASS':'FAIL',differentPixels:diffCount,allowedPixels:4});}
  }
 }
 for(const width of [560,561,760,761,900,901,980,981,1280,1281]){await page.setViewportSize({width,height:900});for(const name of ['fund','weekly','members','cooking','platform']){const c=cases.find(c=>c[0]===name);await reset(c[1]);await measure(name,c[2],width);}}
 await page.setViewportSize({width:1440,height:1000});
 const interaction=async(name,fn)=>{try{interactions.push({name,ok:await fn()});}catch(e){interactions.push({name,ok:false,error:e.message});}};
 await interaction('search focus/cursor after actual input handler',async()=>{await reset({page:'members'});const q=page.locator('[data-member-query]');await q.fill('테스트');return q.evaluate(e=>document.activeElement===e&&e.selectionStart===3&&e.value==='테스트');});
 await interaction('filter + pagination state',async()=>{await reset({page:'members'});await page.locator('[data-member-role]').selectOption('member');await page.locator('[data-list-key="members"][data-list-page="2"]').click();return page.evaluate(()=>__axeTest.state.memberRole==='member'&&__axeTest.state.memberPage===2&&document.querySelector('[data-member-role]').value==='member');});
 await interaction('dropdown open/close actual handlers',async()=>{await reset({});await page.locator('[data-action="toggle-account-menu"]').click();const open=await page.locator('.runtime-account-menu').isVisible();await page.locator('.main').click({position:{x:5,y:5}});return open&&await page.locator('.runtime-account-menu').count()===0;});
 await interaction('modal input survives notice-triggered rerender',async()=>{await reset({page:'members'});await page.locator('[data-action="edit-member"]').first().click();const field=page.locator('[name="member_note"]');await field.fill('작성중 fixture');await page.screenshot({path:path.join(out,'screenshots','modal-note-before.png'),animations:'disabled'});await page.evaluate(()=>__axeTest.setNotice('검증 알림'));const after=await field.inputValue();interactionEvidence.push({test:'modal draft',trigger:'setNotice -> production render()',before:'작성중 fixture',after});await page.screenshot({path:path.join(out,'screenshots','modal-note-after.png'),animations:'disabled'});return await page.locator('[role="dialog"]').isVisible()&&after==='작성중 fixture';});
 await interaction('native select value survives full rerender (popup open state NOT automated)',async()=>{await reset({page:'members'});await page.locator('[data-member-role]').selectOption('admin');await page.evaluate(()=>__axeTest.render());return await page.locator('[data-member-role]').inputValue()==='admin';});
 await interaction('mocked member save: payload and modal lifecycle',async()=>{await reset({page:'members'});await page.evaluate(()=>{const s=__axeTest.state;window.__apiCalls=[];window.__apiMock={};const map={getMemberships:'memberships',getModuleCatalog:'modules',getCompanyModules:'modules',getCookingOrderTypes:'cookingOrderTypes',getCookingDiscordGuide:'cookingDiscordConfig',getCookingDiscordConfig:'cookingDiscordConfig',getCompanySettings:'companySettings',getDiscordConnection:'discordConnection',getDiscordChannels:'discordChannels',getDiscordRoles:'discordRoles',getDiscordCompanyConfig:'discordCompanyConfig',getCompanyOnboardingStatus:'onboardingStatus',getCompanySubscription:'currentSubscription',getFundTreasurySnapshot:'fundSnapshot',getFundAdminRequests:'fundRequests',getFundLedgerAttachments:'fundLedgerAttachments',getWebAssetsSnapshot:'assetsSnapshot',getWebAccountsSnapshot:'accountsSnapshot',getQuestionBoard:'questionBoard',getSuggestionBoard:'suggestionBoard'};for(const [key,value] of Object.entries(map))__apiMock[key]=()=>structuredClone(s[value]);__apiMock.updateMembershipNote=(id,note)=>{s.memberships.find(m=>m.id===id).member_note=note;return {};};});await page.locator('[data-action="edit-member"]').first().click();await page.locator('[name="member_note"]').fill('fixture 저장');await page.locator('form[data-form="member"] button[type="submit"]').click();await page.waitForFunction(()=>!__axeTest.state.loading);return page.evaluate(()=>!__axeTest.state.modal&&!__axeTest.state.error&&__apiCalls.filter(c=>c.name==='updateMembershipNote').length===1&&__apiCalls.some(c=>c.name==='updateMembershipNote'&&c.args[0]==='m0'&&c.args[1]==='fixture 저장'));});
 // Production smoke: actual bundled entry/CSS, isolated no-credentials environment.
 if(prod){const p=await context.newPage();const bad=[];p.on('response',r=>{if(r.status()>=400)bad.push(r.url());});p.on('pageerror',e=>bad.push(e.message));await p.goto(prod.url+'/');await p.waitForSelector('.runtime-auth,.runtime-permission');check('production JS rendered',await p.locator('.pwa-boot').count()===0);check('production stylesheet loaded',await p.evaluate(()=>[...document.styleSheets].some(s=>s.href?.includes('/assets/')&&s.cssRules.length>0)));check('production requests',bad.length===0,bad);await p.close();
  // Sabotage only one isolated browser context: missing CSS must be detected, never bless it.
  const c=await browser.newContext();await c.route('**/*',r=>r.request().url().startsWith(prod.url+'/')?(r.request().url().includes('.css')?r.fulfill({status:404,body:'intentional CSS fault'}):r.continue()):r.abort());const p2=await c.newPage();const failures=[];p2.on('response',r=>{if(r.status()>=400)failures.push(r.url());});await p2.goto(prod.url+'/');await p2.waitForTimeout(300);check('negative control: CSS 404 is detected',failures.some(u=>u.includes('.css')));await c.close();
 }else check('production smoke requires successful build',false);
 check('fixture no unexpected browser errors',errors.length===0,errors);
 const geometryFile=path.join(baseline,'geometry.json');let geometryStatus='NOT RUN';if(record||recordGeometry){fs.writeFileSync(geometryFile,JSON.stringify(metrics,null,2));geometryStatus='RECORDED';}else if(sameEnv&&fs.existsSync(geometryFile)){geometryStatus=JSON.stringify(JSON.parse(fs.readFileSync(geometryFile)))===JSON.stringify(metrics)?'PASS':'FAIL';}
 write('geometry',{status:geometryStatus,note:'Exact measured rectangles/columns/overflow comparison in matching environment. Existing defects remain in baseline.'});
 write('dom-structure',{status:checks.every(c=>c.ok)?'PASS':'FAIL',checks});
 write('browser',{status:checks.every(c=>c.ok)&&defects.length===0?'PASS':'FAIL',executionStatus:'PASS',checks,environment,metrics,layoutStatus:defects.length?'FAIL':'PASS',defects,note:'Layout defects are current observations, not silently waived by baseline recording.'});
 write('interaction',{status:interactions.every(c=>c.ok)?'PASS':'FAIL',checks:interactions,evidence:interactionEvidence,notRun:['Native OS select popup-open persistence','Real API/auth/RLS/save integration','IME operating-system composition']});
 write('visual',{status:record?'RECORDED':visual.some(v=>v.status==='FAIL')?'FAIL':visual.some(v=>v.status==='NOT RUN')?'NOT RUN':'PASS',comparisons:visual,environment});
 if(checks.some(c=>!c.ok)||interactions.some(c=>!c.ok)||defects.length||geometryStatus==='FAIL'||visual.some(c=>c.status==='FAIL'))process.exitCode=1;
 else if(visual.some(c=>c.status==='NOT RUN'))process.exitCode=2;
}catch(e){write('browser',{status:'FAIL',error:e.stack,checks,metrics,errors});process.exitCode=1;}finally{await context.close();await browser.close();await host.close();if(prod)await prod.close();}
